name: Pull Request
on:
  pull_request:
    paths-ignore:
      - ".github/renovate*"
      - ".github/workflows/release.yaml"
      - ".github/workflows/renovate.yaml"
      - ".gitignore"
      - ".jujuignore"
  push:
    branches:
      - "renovate/*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/build-and-test.yaml
